### ISSUE TITLE
Blur disappears when opening a new Konsole tab

### ISSUE THREAD

**Issue by IslandC0der** [esjeon/kwin-forceblur#14]
Hi,
Whenever I press Ctrl+Shift+T to open a new Konsole tab, the blur goes away. Closing the previously opened tab doesn't help. If I open a new Konsole window, the blur will apply there normally, but still not on the old one.
I have the "Blur all except matching" option enabled with no window class names (so it applies to all windows).
Thanks in advance! :)
Cheers

**Comment by esjeon** [comment]
Hi.

Konsole natively supports background blurring, which can be enabled by checking `Blur background` in its `Appearance` settings.

As a side note, the cause of this problem is that Konsole resets blur information whenever the current tab is changed. Konsole allows using different profiles per tab, where each profile can have different background blur settings. To support this, Konsole must reapply blur settings whenever user switches between tabs.

**Comment by IslandC0der** [comment]
Enabling the native blur fixes it, thanks!
Closing.
