### ISSUE TITLE
Doesn't work properly with GTK CSD apps on Plasma 5.18

### ISSUE THREAD

**Issue by a-parhom** [esjeon/kwin-forceblur#7]
It seems, that the shadow applied to CSD windows is treated as if it is the window itself:

![tilix](https://user-images.githubusercontent.com/13824167/78829354-dd49cc80-79ee-11ea-95ea-3a514404ac95.png)

**Comment by esjeon** [comment]
Okay, the cause of the problem is very very simple: CSD shadow is actually a part of its parent window, and shares the pixel buffer. KWin internally compensates for this in its WM logic, but [the blur plugin uses the original window geometry][1].

One way to fix this is to properly set `_KDE_NET_WM_BLUR_BEHIND_REGION` to the actual window region, but one also should keep the value in sync whenever the window is resized. This instantly blows up the complexity of the script, but, yeah, worth a shot.

[1]: https://github.com/KDE/kwin/blob/44c558c31f09500efe4904e1f2dcc7d54b59b6dc/effects/blur/blur.cpp#L428

**Comment by a-parhom** [comment]
This commit works great, thank you!

**Comment by esjeon** [comment]
This issue has been resolved.
